# GitHub Sponsors funding file
# Uncomment and add your sponsor links

# github: [username]
# patreon: username
# open_collective: active-wing
# ko_fi: username
# custom: ["https://www.buymeacoffee.com/username", "https://paypal.me/username"]
